=== Valkenzo/U7W4RZWebXML/U7W4RZ_1008/U7W4RZ_kurzusfelvetel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:simpleType name="tanevTipus">
        <xs:restriction base="xs:gYear">
            <xs:minInclusive value="2000"/>
            <xs:maxInclusive value="2100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="egyetemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Miskolci Egyetem"/>
            <xs:enumeration value="Budapesti MÅ±szaki Egyetem"/>
            <xs:enumeration value="Debreceni Egyetem"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{1,3}:[0-9]{1,2}:[0-9]{2}-[0-9]{1,2}:[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="igenNemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen"/>
            <xs:enumeration value="nem"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="hallgato">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hnev" type="xs:string"/>
                <xs:element name="szulev" type="xs:gYear"/>
                <xs:element name="szak">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="evf" type="xs:gYear" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="kurzus">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kurzusnev" type="xs:string"/>
                <xs:element name="kredit" type="xs:nonNegativeInteger"/>
                <xs:element name="hely" type="xs:string"/>
                <xs:element name="idopont" type="idTipus"/>
               
                <xs:choice>
                    <xs:element name="oktato" type="xs:string"/>
                    <xs:element name="oraado" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="jovahagyas" type="igenNemTipus" use="optional"/>
            <xs:attribute name="nyelv" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="kurzusok">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kurzus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="U7W4RZ_kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hallgato"/>
                <xs:element ref="kurzusok"/>
            </xs:sequence>
            <xs:attribute name="tanev" type="tanevTipus" use="required"/>
            <xs:attribute name="egyetem" type="egyetemTipus" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Valkenzo/U7W4RZWebXML/U7W4RZ_1008/U7W4RZ_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<U7W4RZ_kurzusfelvetel
    tanev="2025"
    egyetem="Miskolci Egyetem"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="U7W4RZ_kurzusfelvetel.xsd">

    <hallgato>
        <hnev>Valko Attila Laszlo</hnev>
        <szulev>1991</szulev>
        <szak evf="2023">Mernokinformatikus</szak>
    </hallgato>

    <kurzusok>

        <kurzus jovahagyas="nem" nyelv="magyar">
            <kurzusnev>Elektrotechnika-elektronika</kurzusnev>
            <kredit>5</kredit>
            <hely>E3</hely>
            <idopont>H:8:00-9:50</idopont>
            <oktato>Szabo Norbert</oktato>
        </kurzus>

        <kurzus jovahagyas="nem" nyelv="magyar">
            <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>E32</hely>
            <idopont>K:10:00-12:00</idopont>
            <oktato>Kunné Dr. Tamas Judit</oktato>
        </kurzus>

        <kurzus>
            <kurzusnev>Mobil programozási alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>L101</hely>
            <idopont>H:16:00-18:00</idopont>
            <oraado>Dr. Agardi Anita</oraado>
        </kurzus>

        <kurzus>
            <kurzusnev>Web technológiák 1.</kurzusnev>
            <kredit>5</kredit>
            <hely>E5</hely>
            <idopont>H:10:00-12:00</idopont>
            <oraado>Dr. Agardi Anita</oraado>
        </kurzus>

        <kurzus>
            <kurzusnev>Webes adatkezelő környezetek</kurzusnev>
            <kredit>5</kredit>
            <hely>A1/310</hely>
            <idopont>SZE:8:00-10:00</idopont>
            <oktato>Dr. Kovacs Laszlo Jozsef</oktato>
        </kurzus>

        <kurzus>
            <kurzusnev>Windows rendszergazda</kurzusnev>
            <kredit>5</kredit>
            <hely>L103</hely>
            <idopont>K:16:00-18:00</idopont>
            <oktato>Dr. Wagner Gyorgy</oktato>
        </kurzus>

        <kurzus>
            <kurzusnev>Angol muszaki szaknyelv 1.</kurzusnev>
            <kredit>0</kredit>
            <hely>A1/316</hely>
            <idopont>H:12:00-14:00</idopont>
            <oktato>Pataki Janosne</oktato>
        </kurzus>

    </kurzusok>

</U7W4RZ_kurzusfelvetel>
